site_name: Java
site_url: https://anand-chitte.github.io/JavaDoc/

nav:
  - Home: index.md
  - Java:
    - Introduction: java/introduction.md
    - How Java Works: java/How Java Works.md
    - JVM: java/Java Virtual Machine (JVM).md
    - Garbage Collector: java/Garbage Collector.md
    - Data Type: java/DataType.md
    - Operators: java/Operators.md
    - Casting: java/Casting.md
    - Access Modifier: java/AccessModifier.md
    - Object-Oriented Programming: java/Object-Oriented Programming.md
    - Constructor: java/Constructor.md
    - Method overloading & overriding: java/Method overloading & overiding.md
    - Static & Final Keyword: java/StaticFinalKeyword.md
    - String: java/String.md
    - Interface: java/Interface.md
    - Exception: java/Exception in Java.md
    - Generics: java/Generics.md
    - Functional Interface: java/FunctionalInterface.md
    - Lambda Expression: java/LambdaExpression.md
  - Thread:
      - Introduction: java/thread/Thread.md
      - Synchronization: java/thread/Synchronization.md
      - Locks: java/thread/Locks.md
      - Executor Frameworks: java/thread/ExecutorFramework.md
  - Collection Framework:
      - Introduction: java/collection/Collection Framework.md
      - Hashmap: java/collection/Hashmap.md
      - Comparable vs Compartor: java/collection/Comparable vs Compartor.md
      - Iterator vs Iterable: java/collection/Iterator & Iterable.md
  - Stream:
      - Introduction: java/stream/Stream.md
      - Creating Stream: java/stream/CreatingStream.md
      - Intermediate Operation: java/stream/IntermediateOperation.md
      - Terminal Operation: java/stream/TerminalOperation.md
      - Stream API With Primitive Data Types: java/stream/StreamWithPrimitiveDataType.md
  - Other:
       - Marker Interface: java/other/MarkerInterface.md
       - SOLID: java/other/Solid.md
       - Reflection API: java/other/ReflectionAPI.md
       - Design Pattern: java/other/DesignPattern.md
       - Functional Programming: java/other/FunctionalProgramming.md
       - Java Versions: java/other/Versions.md
       - Flight Recorder: java/other/FlightRecorder.md
  - Hibernate:
      - Introduction: hibernate/Introduction.md
      - Configuration: hibernate/Configuration.md
      - CRUD: hibernate/CRUD.md
      - Relationship: hibernate/Relationship.md
  - Spring:
      - Introduction: spring/Introduction.md.md
      - Spring Container: spring/Spring Container.md
      - Bean: spring/Bean.md
      - Spring Boot: spring/Spring Boot.md
      - Spring Profiles: spring/Spring Profiles.md
      - Spring Actuator: spring/Actuator.md
      - ORM: spring/ORM.md
      - JPA: spring/JPA.md
      - RestTemplate: spring/RestTemplate.md
      - WebClient: spring/WebClient.md
      - Spring boot annotations: spring/Spring boot annotations.md
      - Spring Security: spring/Spring Security.md
      - Spring MVC: spring/SpringMVC.md
      - JSP: spring/JSP.md
      - OAuth2: spring/Oauth.md
      - JWT: spring/JWT.md
      - Keycloak: spring/Keycloak Implementation.md
      - Scheduling: spring/Scheduling.md
      - Multithreading: spring/MultithreadingSpringBoot.md
      - Correlation ID: spring/CorrelationId.md
  - Microservices:
      - Introduction: microservices/Introduction.md.md
      - Eureka Server: microservices/EurekaServer.md
      - Configserver: microservices/ConfigServer.md
      - Resiliency: microservices/Resiliency.md
      - Spring Cloud Gateway: microservices/Gateway.md
      - FeignClient: microservices/FeignClient.md
      - SpringCloudSleuth: microservices/SpringCloudSleuth.md
      - Spring Cloud Function: microservices/SpringCloudFunction.md
      - Spring Cloud Stream: microservices/SpringCloudStream.md
      - Design Pattern: microservices/DesignPattern.md
  - PostgreSQL:
      - Dataset: postgres/Dataset.md
      - Question: postgres/Question.md
      - Answer: postgres/Answer.md
  - Other:
    - HTTP: other/HTTP.md
    - Maven: other/Maven.md
    - Git: other/Git.md
    - Docker: other/Docker.md
    - Redis: other/Redis.md
    - RabbitMQ: other/RabbitMQ.md
    - AWS: other/AWS.md
    - Agile: other/Agile.md
    - Flowchart: other/Flowchart.md
  - Interview:
    - Introduce Yourself: interview/IntroduceYourself.md
    - Question: interview/Question.md
    - Programs: interview/Programs.md
    - Practice: interview/Practice.md
    - SQLSchema: interview/SQLSchema.md
    - References: interview/References.md
#  - Project:
#    - ILMS: projects/ILMS.md
#    - Fastag: projects/Fastag.md
  - CBS:
    - CBS: cbs/CBS.md
    - CBS Developer Document: cbs/CBSDevelopment.md
    - HLD: cbs/HLD.md
    - LLD: cbs/LLD.md
    - CBS Developer Document(Blockchain): cbs/CBSDevelopmentBlockchain.md
extra_css:
  - css/custom.css
extra:
  manifest_file: "manifest.json"
theme:
  name: readthedocs
#  color_mode: auto
#  user_color_mode_toggle: true
  highlightjs: true
  hljs_languages:
    - java
    - properties
    - bash
    - shell
plugins:
#  - search
  - mermaid2
#markdown_extensions:
#  - pymdownx.superfences
#  - pymdownx.highlight
#  - pymdownx.inlinehilite
