site_name: Java
site_url: https://anand-chitte.github.io/JavaDoc/

nav:
  - Java:
    - Introduction: java/introduction.md
    - How Java Works: java/How Java Works.md
    - JVM: java/Java Virtual Machine (JVM).md
    - Object-Oriented Programming: java/Object-Oriented Programming.md
    - Method overloading & overiding: java/Method overloading & overiding.md
    - Static & Final Keyword: java/StaticFinalKeyword.md
    - String: java/String.md
    - Interface: java/Interface.md
    - Exception in Java: java/Exception in Java.md
    - Generics: java/Generics.md
    - Collection Framework: java/Collection Framework.md
    - StreamsLambdaFuncational: java/StreamsLambdaFunctional.md
    - Stream: java/Stream.md
    - Lambda Expression: java/LambdaExpression.md
    - Functional Interface: java/FunctionalInterface.md
    - Hashmap: java/Hashmap.md
    - Comparable vs Compartor: java/Comparable vs Compartor.md
    - Iterator vs Iterable: java/Iterator & Iterable.md
    - Thread: java/Thread.md
    - Programming Questions: java/ProgrammingQuestions.md
  - Spring:
      - Introduction: spring/Introduction.md
      - Spring Container: spring/Spring Container.md
      - Spring Boot: spring/Spring Boot.md
      - Spring Profiles: spring/Spring Profiles.md
      - RestTemplate: spring/RestTemplate.md
      - WebClient: spring/WebClient.md
      - Spring boot annotations: spring/Spring boot annotations.md
      - Spring Security: spring/Spring Security.md
      - Keycloak: spring/Keycloak Implementation.md
      - Correlation ID: spring/CorrelationId.md
  - Microservices:
      - Introduction: microservices/Introduction.md
      - Eureka Server: microservices/EurekaServer.md
      - Configserver: microservices/ConfigServer.md
      - Resiliency: microservices/Resiliency.md
      - Spring Cloud Gateway: microservices/Gateway.md
      - FeignClient: microservices/FeignClient.md
      - Spring Cloud Function: microservices/SpringCloudFunction.md
      - Spring Cloud Stream: microservices/SpringCloudStream.md
  - Other:
    - Redis: other/Redis.md
    - RabbitMQ: other/RabbitMQ.md

extra_css:
  - css/custom.css
extra:
  manifest_file: "manifest.json"
theme:
  name: readthedocs
#  color_mode: auto
#  user_color_mode_toggle: true
  highlightjs: true
  hljs_languages:
    - java
    - properties
    - bash
    - shell